apiVersion: v1
kind: Namespace
metadata:
  name: spotify-utils
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spotify-auth-cache
  namespace: spotify-utils
spec:
  resources:
    requests:
      storage: 10Ki
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: like-playlist
  namespace: spotify-utils
spec:
  concurrencyPolicy: Replace
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            spotify-utils-auth: expose
        spec:
          containers:
            - name: spotifyutils
              image: xor110/spotifyutils:v0.3
              command:
                - sh
                - -c
              args:
                - spotifyutils --discord-user 206788464472096769 --url https://spotify-utils.is.erj4.uk/callback like-playlist --playlist=$(date +%Y)
              volumeMounts:
                - mountPath: /spotifyutils
                  name: credentials
                - mountPath: /spotifyutils/.cache
                  name: auth-cache
              ports:
                - containerPort: 30001
                  name: http
          volumes:
            - name: credentials
              secret:
                secretName: spotify-credentials
            - name: auth-cache
              persistentVolumeClaim:
                claimName: spotify-auth-cache
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: spotify-utils-auth
  namespace: spotify-utils
spec:
  selector:
    spotify-utils-auth: expose
  ports:
    - name: http
      port: 80
      targetPort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotify-utils
  namespace: spotify-utils
spec:
  rules:
    - host: spotify-utils.is.erj4.uk
      http:
        paths:
          - pathType: Prefix
            path: "/callback"
            backend:
              service:
                name: spotify-utils-auth
                port:
                  name: http
